import { StyleSheet } from 'react-native';

import { GREEN_BADGE, GREEN_DARK, GREEN_LIGHT, GREEN_MID } from '@/constants/homeTypes';

export const sensorStyles = StyleSheet.create({
  card: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 14,
    marginHorizontal: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.07,
    shadowRadius: 4,
    elevation: 2,
  },
  iconBadge: {
    width: 36,
    height: 36,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  label: {
    fontSize: 11,
    color: '#777777',
    fontWeight: '500',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  valueRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    marginBottom: 8,
  },
  value: {
    fontSize: 32,
    fontWeight: '700',
    color: '#1A1A1A',
    lineHeight: 36,
  },
  unit: {
    fontSize: 14,
    fontWeight: '600',
    color: '#555555',
    marginBottom: 4,
    marginLeft: 2,
  },
  tag: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 20,
    paddingHorizontal: 8,
    paddingVertical: 3,
    alignSelf: 'flex-start',
  },
  tagText: {
    fontSize: 10,
    fontWeight: '600',
  },
});

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F6F4',
  },
  header: {
    backgroundColor: GREEN_DARK,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    gap: 10,
  },
  headerLogo: {
    width: 44,
    height: 44,
  },
  headerTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '700',
  },
  content: {
    padding: 16,
    paddingBottom: 32,
  },
  greetingCard: {
    backgroundColor: GREEN_DARK,
    borderRadius: 18,
    padding: 20,
    marginBottom: 14,
  },
  goodDay: {
    color: '#A5D6A7',
    fontSize: 13,
    fontWeight: '500',
  },
  userName: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '700',
    marginTop: 2,
    marginBottom: 6,
  },
  dateTime: {
    color: '#81C784',
    fontSize: 12,
    marginBottom: 12,
  },
  storageBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: GREEN_BADGE,
    alignSelf: 'flex-start',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 5,
    gap: 5,
  },
  storageBadgeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  sensorRow: {
    flexDirection: 'row',
    marginBottom: 12,
    marginHorizontal: -4,
  },
  moistureCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 16,
    marginBottom: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.07,
    shadowRadius: 4,
    elevation: 2,
  },
  moistureLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  moistureIconBadge: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: GREEN_LIGHT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  moistureLabel: {
    fontSize: 11,
    color: '#777777',
    fontWeight: '500',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  moistureValueRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  moistureValue: {
    fontSize: 32,
    fontWeight: '700',
    color: '#1A1A1A',
    lineHeight: 36,
  },
  moistureUnit: {
    fontSize: 14,
    fontWeight: '600',
    color: '#555555',
    marginBottom: 4,
    marginLeft: 2,
  },
  detailsBtn: {
    backgroundColor: GREEN_LIGHT,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  detailsBtnText: {
    color: GREEN_MID,
    fontSize: 12,
    fontWeight: '600',
  },
  aboutCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  aboutTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#1A1A1A',
    marginBottom: 12,
  },
  aboutBody: {
    fontSize: 13,
    color: '#555555',
    lineHeight: 20,
    marginBottom: 10,
  },
});